spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 935084453952-s700kmpuluo3hamu57q1gp647vprp5i4.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
mail:
  address:
    admin: hanggiil51@gmail.com
