spring:
  profiles:
    include: oauth
  datasource:
    url: jdbc:h2:tcp://localhost/~/oneroom
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      hbm2ddl:
        auto: update
#      ddl-auto: create
    properties:
      hibernate:
#         show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

jwt:
  key: "kevin1234123412341234123412341234"
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420